[phases.setup]
aptPkgs = ["tesseract-ocr", "tesseract-ocr-eng", "tesseract-ocr-osd"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"